//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consultorioMedico
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public Cita()
        {
            this.ExpFisica = new List<ExpFisica>();
        }
    
        public int ID { get; set; }
        public System.DateTime fecha { get; set; }
        public string descripcion { get; set; }
        public bool status { get; set; }
        public int ID_Paciente { get; set; }
        public int ID_Medico { get; set; }
        public Nullable<int> ID_Horario { get; set; }
    
        public   Horario Horario { get; set; }
        public   Medico Medico { get; set; }
        public   Paciente Paciente { get; set; }
        public   List<ExpFisica> ExpFisica { get; set; }
    }
}
