//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consultorioMedico
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        public Cuenta()
        {
            this.Medico = new List<Medico>();
            this.Paciente = new List<Paciente>();
            this.Secretario = new List<Secretario>();
        }
    
        public int ID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int ID_TipoCuenta { get; set; }
    
        public   TipoCuenta TipoCuenta { get; set; }
        public   List<Medico> Medico { get; set; }
        public   List<Paciente> Paciente { get; set; }
        public   List<Secretario> Secretario { get; set; }
    }
}
