//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consultorioMedico
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpFisica
    {
        public int ID { get; set; }
        public string estudios { get; set; }
        public string evolucion { get; set; }
        public double temperatura { get; set; }
        public int frecCardiaca { get; set; }
        public int frecRespiratoria { get; set; }
        public double estatura { get; set; }
        public double peso { get; set; }
        public Nullable<double> perToraxIns { get; set; }
        public Nullable<double> perToraxExp { get; set; }
        public Nullable<double> perAbdomen { get; set; }
        public double presionSis { get; set; }
        public double presionDias { get; set; }
        public int ID_Cita { get; set; }
        public string odontograma { get; set; }
    
        public   Cita Cita { get; set; }
    }
}
