//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consultorioMedico
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horario
    {
        public Horario()
        {
            this.Cita = new List<Cita>();
        }
    
        public int ID { get; set; }
        public int ID_Medico { get; set; }
        public string dia { get; set; }
        public int hora { get; set; }
    
        public   List<Cita> Cita { get; set; }
        public   Medico Medico { get; set; }
    }
}
