//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consultorioMedico
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interrogatorio
    {
        public int ID { get; set; }
        public string alimentacion { get; set; }
        public bool deporte { get; set; }
        public bool drogas { get; set; }
        public bool toma { get; set; }
        public bool fuma { get; set; }
        public bool enfMental { get; set; }
        public bool enfRinon { get; set; }
        public bool enfCorazon { get; set; }
        public bool cancer { get; set; }
        public bool diabetes { get; set; }
        public bool enfCerVas { get; set; }
        public int ID_Paciente { get; set; }
    
        public   Paciente Paciente { get; set; }
    }
}
