//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consultorioMedico
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicamentoReceta
    {
        public int ID { get; set; }
        public string medicamento { get; set; }
        public string dosis { get; set; }
        public string horario { get; set; }
        public int ID_Receta { get; set; }
    
        public   Receta Receta { get; set; }
    }
}
