//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consultorioMedico
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class consulmedicoEntities : DbContext
    {
        public consulmedicoEntities()
            : base("name=consulmedicoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cita> Cita { get; set; }
        public DbSet<Cuenta> Cuenta { get; set; }
        public DbSet<ExpFisica> ExpFisica { get; set; }
        public DbSet<Horario> Horario { get; set; }
        public DbSet<Interrogatorio> Interrogatorio { get; set; }
        public DbSet<MedicamentoReceta> MedicamentoReceta { get; set; }
        public DbSet<Medico> Medico { get; set; }
        public DbSet<MedicoSecretario> MedicoSecretario { get; set; }
        public DbSet<Paciente> Paciente { get; set; }
        public DbSet<Receta> Receta { get; set; }
        public DbSet<Secretario> Secretario { get; set; }
        public DbSet<TipoCuenta> TipoCuenta { get; set; }
        public DbSet<Vacuna> Vacuna { get; set; }
        public DbSet<VacunaPaciente> VacunaPaciente { get; set; }
    }
}
