//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consultorioMedico
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public Paciente()
        {
            this.Cita = new List<Cita>();
            this.Interrogatorio = new List<Interrogatorio>();
            this.Receta = new List<Receta>();
            this.VacunaPaciente = new List<VacunaPaciente>();
        }
    
        public int ID { get; set; }
        public int ID_Cuenta { get; set; }
        public string nombre { get; set; }
        public string apellidoMaterno { get; set; }
        public string apellidoPaterno { get; set; }
        public string tipoSangre { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public string sexo { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public int ID_Medico { get; set; }
    
        public   List<Cita> Cita { get; set; }
        public   Cuenta Cuenta { get; set; }
        public   List<Interrogatorio> Interrogatorio { get; set; }
        public   Medico Medico { get; set; }
        public   List<Receta> Receta { get; set; }
        public   List<VacunaPaciente> VacunaPaciente { get; set; }
    }
}
