//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consultorioMedico
{
    using System;
    using System.Collections.Generic;
    
    public partial class Secretario
    {
        public Secretario()
        {
            this.MedicoSecretario = new List<MedicoSecretario>();
        }
    
        public int ID { get; set; }
        public int ID_Cuenta { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public string telefono { get; set; }
        public string turno { get; set; }
    
        public   Cuenta Cuenta { get; set; }
        public   List<MedicoSecretario> MedicoSecretario { get; set; }
    }
}
