//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consultorioMedico
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacuna
    {
        public Vacuna()
        {
            this.VacunaPaciente = new List<VacunaPaciente>();
        }
    
        public int ID { get; set; }
        public string nombre { get; set; }
    
        public   List<VacunaPaciente> VacunaPaciente { get; set; }
    }
}
